name: LUA

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:
    paths-ignore:
      - '**.md'
      - '**.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hash
        run: |
          sha256sum -b localonly.bat > checksums.sha256
          sha256sum -b autounattend.xml >> checksums.sha256
      - uses: actions/upload-artifact@v4
        with:
          name: LUA
          path: |
            localonly.bat
            checksums.sha256
            autounattend.xml
          if-no-files-found: error
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            localonly.bat
            checksums.sha256
            autounattend.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
